name: Build & Push Backend Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout source code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Login GCP using Service Account
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3️⃣ Setup gcloud
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    # 4️⃣ Configure Docker for Artifact Registry
    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    # 5️⃣ Build & Push Backend Image
    - name: Build & Push Backend
      run: |
        cd jobquestbackend
        IMAGE=asia-southeast1-docker.pkg.dev/jobquest-ptud-hai/jobquest-repo/backend:v17
        docker build -t $IMAGE .
        docker push $IMAGE
